/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 facebook.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Scene = (props) => {
  const { nodes, materials } = useGLTF("/facebook.glb");
  const groupRef = useRef();

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.004;
    }
  });
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group
        position={[0.094, 0.436, 0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.004}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <mesh
              // castShadow
              receiveShadow
              geometry={nodes["Facebook_Logo_01_-_Default_0001"].geometry}
              material={materials["01_-_Default.001"]}
              position={[-69.275, 389.436, -208.849]}
              rotation={[0, -0.15, 0]}
              scale={1.5}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default Scene;

useGLTF.preload("./facebook.glb");
